spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alura_foro
    username: root
    password: root
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never

api:
  security:
    secret: ${JWT_SECRET:123456}
